services:
  db:
    image: postgres:16
    container_name: databaseShieldTask
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dbforTechnicalTask"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - shield-net

volumes:
  pgdata:

networks:
  shield-net:
